# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
project_name: generator
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -X config.Version={{.Version}} -X config.BuildTag={{.FullCommit}} -X config.BuildTime={{ .Date }} -X config.CommitTime={{ .CommitDate }}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - data/config.example.toml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
      # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
      # GOARM of the built binaries/packages that should be used.
    goarm: ''
    image_templates:
      - "hitokoto/generator:latest"
      - "hitokoto/generator:{{ .Tag }}"
      - "hitokoto/generator:{{ .Tag }}-{{ .Env.GO_VERSION }}"
      - "hitokoto/generator:v{{ .Major }}"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=cn.hitokoto.generator.image.created={{.Date}}"
      - "--label=cn.hitokoto.generator.image.title={{.ProjectName}}"
      - "--label=cn.hitokoto.generator.image.revision={{.FullCommit}}"
      - "--label=cn.hitokoto.generator.image.version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - data/config.example.toml
