on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Go
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Cache Go module
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: |
          go mod tidy
      - name: Check Make is installed
        run: make -v
      - name: Build
        run: make build
      - name: Test
        run: go test -v ./...
